### ISSUE TITLE
Messages to be delivered later

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/ralph-hubot#5]
We often say, e.g. "Future Joe - that cat-v guy thinks a Web framework written in shell doesn't suck!", but the Joe of the future doesn't necessarily read the scrollback.

Hubot should detect uses of "Future X", where X is a person's name, and store them; when X next comes back from idle/signs online, it should deliver the message.

**Comment by gabebw** [comment]
There's a spike in this branch: https://github.com/thoughtbot/ralph-hubot/tree/gbw-later-messages

**Comment by gabebw** [comment]
Sort of fixed in #6 - except that the robot doesn't detect when users re-enter a room.

**Comment by gabebw** [comment]
This works now.
