### ISSUE TITLE
For "Future Gabe" messages, have Ralph provide a link to Campfire so the target has context

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/ralph-hubot#8]
Sometimes the delivered messages from Ralph are just:

> Ralph: [time] | ^ future Gabe

which isn't very helpful at all. Instead, we can provide a URL to Campfire. Campfire URLs look like this: https://thoughtbot.campfirenow.com/room/344621/transcript/2014/02/04#message_1185099535. The `_111111` at the end is the message ID, which I believe we can get via `msg.message.id`.

I haven't verified that, but here's the relevant line in the Campfire adapter: https://github.com/github/hubot/blob/master/src/message.coffee#L20

**Comment by calebhearth** [comment]
`future` has been removed; can this be closed?

**Comment by gabebw** [comment]
Yup.
